/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorUsuarios;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jose,Marco,Yuliana,Elver
 */
public class Usuarios extends javax.swing.JInternalFrame {
    private ControladorUsuarios cusuarios;
    private String txtespe;
    private String txtTipo;

    public JComboBox<String> getComboespe() {
        return comboespe;
    }

    public JComboBox<String> getCombotipo() {
        return combotipo;
    }

    public void setTxtMensajeC(String txtMensajeC) {
        this.txtMensajeC.setText(txtMensajeC);
    }

    
    
    public void setTxtmensaje(String txtmensaje) {
        this.txtmensaje.setText(txtmensaje);
    }

 
    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JTextField getTxtcedula() {
        return txtcedula;
    }

    public JTextField getTxtcontra() {
        return txtcontra;
    }

    public JTextField getTxtcorreo() {
        return txtcorreo;
    }

    public JDateChooser getTxtFecha() {
        return txtFecha;
    }

   

    public JTextField getTxtnombre() {
        return txtnombre;
    }

    public JTextField getTxtusuario() {
        return txtusuario;
    }

    public JTextField getTxtCondigo() {
        return txtCondigo;
    }


   public JTextField getTxtSalario() {
        return txtSalario;
    }

    public String getTxtespe() {
        return txtespe;
    }

    public String getTxtTipo() {
        return txtTipo;
    }
   
   
    public Usuarios() {
        initComponents();
              this.getContentPane().setBackground(new Color(85,151,248));
        cusuarios = new ControladorUsuarios();
        this.cargarTamanio();
           txtSalario.setVisible(false);
             txtCondigo.setVisible(false);
               comboespe.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtnombre = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtcontra = new javax.swing.JPasswordField();
        txtCondigo = new javax.swing.JTextField();
        comboespe = new javax.swing.JComboBox<>();
        txtSalario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtmensaje = new javax.swing.JLabel();
        txtMensajeC = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(85, 151, 248));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setTitle("Usuarios");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnombre.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 245, 50));

        txtcedula.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtcedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Numero de cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 245, 50));

        txtTelefono.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Numero de telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 245, 50));

        combotipo.setBackground(new java.awt.Color(255, 255, 255));
        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de usuario" }));
        combotipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotipoItemStateChanged(evt);
            }
        });
        getContentPane().add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 245, 50));

        txtcorreo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtcorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Correo electronico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 245, 50));

        txtusuario.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtusuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 245, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobar.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 30, -1));

        txtcontra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        txtcontra.setPreferredSize(new java.awt.Dimension(12, 44));
        getContentPane().add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 245, 50));

        txtCondigo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtCondigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Código de colegio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtCondigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 245, 50));

        comboespe.setBackground(new java.awt.Color(255, 255, 255));
        comboespe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidad" }));
        getContentPane().add(comboespe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 245, 50));

        txtSalario.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        txtSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Salario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12))); // NOI18N
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 245, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 75, 65));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icon-merge.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 75, 65));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro-Save-Blue-256.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 75, 65));

        txtmensaje.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 20));

        txtMensajeC.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(txtMensajeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 20));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contr-cam.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 400, 69, 65));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/57477.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 400, -1, 65));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 245, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.txtnombre.setText(null);
       this.txtcedula.setText(null);
       this.txtTelefono.setText(null);
       this.txtcontra.setText(null);
       this.txtcorreo.setText(null);
       this.txtusuario.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ( cusuarios.agregar(this)==false) {
            txtMensajeC.setBackground(new Color(153,51,0));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 public void cargarTamanio(){
            combotipo.addItem("Secretaria");
            combotipo.addItem("Medico");
            comboespe.addItem("Medicina General");
            comboespe.addItem("Pediatría");
            comboespe.addItem("Neurología");
            comboespe.addItem("Cardiología");
            comboespe.addItem("Cirugía General");
            comboespe.addItem("Ginecología");
            
        }

    private void combotipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotipoItemStateChanged
        if (combotipo.getSelectedItem()=="Medico") {
            txtSalario.setVisible(true);
             txtCondigo.setVisible(true);
               comboespe.setVisible(true);
        }else{
            if (combotipo.getSelectedItem()=="Secretaria") {
                  txtSalario.setVisible(false);
             txtCondigo.setVisible(false);
               comboespe.setVisible(false);
            }
        }
    }//GEN-LAST:event_combotipoItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cusuarios.comprobarUs(this)==true) {
           
            txtmensaje.setForeground(Color.GREEN);
        }else{
      txtmensaje.setForeground(new Color(153,51,0));
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cusuarios.eliminar(this)==true) {
            JOptionPane.showMessageDialog(null, "Se elimino el usuario de la base de datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed

    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      frmCambioPass cambio= new frmCambioPass();
      FrmConsultorio.Escritorio.add(cambio);
      cambio.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       FrmBuscarUsuario buscar= new FrmBuscarUsuario();
               FrmConsultorio.Escritorio.add(buscar);
               buscar.show();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboespe;
    public static javax.swing.JComboBox<String> combotipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCondigo;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JLabel txtMensajeC;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JLabel txtmensaje;
    private javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
